version: '3.3'

services:
  db:
    image: mongo:4.2.3
    volumes:
      - altszama-mongodb-volume:/data/db
    restart: always
    env_file: .env

  backend:
    depends_on:
      - db
    image: "altszama-backend"
    restart: always
    env_file: .env
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      VAPID_PUBLIC_KEY: $VAPID_PUBLIC_KEY
      VAPID_PRIVATE_KEY: $VAPID_PRIVATE_KEY
      VAPID_SUBJECT: $VAPID_SUBJECT
      JWT_SIGNING_KEY: $JWT_SIGNING_KEY
      ORIGIN_URL: $ORIGIN_URL

  frontend:
    depends_on:
      - backend
    image: "altszama-frontend"
    restart: always
    env_file: .env
    environment:
      VUE_APP_GOOGLE_CLIENT_ID: $VUE_APP_GOOGLE_CLIENT_ID
      VUE_APP_SENTRY_URL: $VUE_APP_SENTRY_URL
      VUE_APP_VAPID_PUBLIC_KEY: $VUE_APP_VAPID_PUBLIC_KEY

  reverse-proxy:
    depends_on:
      - backend
      - frontend
    image: "altszama-reverse-proxy"
    ports:
      - "127.0.0.1:${TARGET_PORT}:80"

volumes:
  altszama-mongodb-volume: {}
