version: 2
jobs:
  test:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    docker:
    - image: circleci/openjdk:8u212-stretch

    steps:
    - checkout

    - restore_cache:
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - restore_cache:
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

    - run:
        name: Build backend app
        command: |
          cd ./backend-app
          ./gradlew --console=plain clean build
          cd ../

    # - run: docker push konkit/altszama:$CIRCLE_WORKFLOW_ID
#    - setup_remote_docker

#    - run: echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY_URL --username $DOCKER_REGISTRY_USER --password-stdin

    - run:
        name: Build frontend app
        command: |
          cd ./vue-app
          npm run build
          cd ../

    - save_cache:
        paths:
        - ~/.gradle/wrapper
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - save_cache:
        paths:
        - ~/.gradle/caches
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

  deploy:
    machine:
      enabled: true
    steps:
    - add_ssh_keys

    - run:
        name: known_hosts sadness
        command: ssh-keyscan -H $SITE_SSH_HOST >> ~/.ssh/known_hosts

    - run:
        name: Do the upgrade
        command: |
          ssh $SITE_SSH_USER@$SITE_SSH_HOST "cd /var/app/altszama && sh update.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - test
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master
