version: 2
jobs:
  test:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    docker:
    - image: cimg/openjdk:11.0-node
    - image: circleci/mongo:4.2.3

    steps:
    - checkout
    - setup_remote_docker

    - restore_cache:
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - restore_cache:
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

    - run:
        name: Build docker images
        command: |
          set -e
          ./buildDockerImages.sh

    - save_cache:
        paths:
        - ~/.gradle/wrapper
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - save_cache:
        paths:
        - ~/.gradle/caches
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

  deploy:
    machine:
      enabled: true
    steps:
    - add_ssh_keys

    - run:
        name: known_hosts sadness
        command: ssh-keyscan -H $SITE_SSH_HOST >> ~/.ssh/known_hosts

    - run:
        name: Do the upgrade
        command: |
          ssh $SITE_SSH_USER@$SITE_SSH_HOST "cd /var/app/altszama && sh update.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - test
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master
