version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    docker:
    - image: circleci/openjdk:8u212-stretch
    - image: circleci/node:9.9.0

    steps:
    - checkout

    - restore_cache:
        key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

    - restore_cache:
        key: v1-gradle-cache-{{ checksum "build.gradle" }}

    - run:
        name: Fill application-production.properties
        command: |
          echo "altszama.gcmServerKey=$GCM_SERVER_KEY" > ./backend-app/src/main/resources/application-production.properties
          echo "altszama.databaseName=$DATABASE_NAME" >> ./backend-app/src/main/resources/application-production.properties
          echo "altszama.googleClientId=$GOOGLE_CLIENT_ID" >> ./backend-app/src/main/resources/application-production.properties
          echo "altszama.googleClientSecret=$GOOGLE_CLIENT_SECRET" >> ./backend-app/src/main/resources/application-production.properties

    - run:
        name: Fill .env.production.local
        command: |
          echo "VUE_APP_BACKEND_URL=$VUE_APP_BACKEND_URL" > ./vue-app/.env.production.local
          echo "VUE_APP_GCM_SENDER_ID=$VUE_APP_GCM_SENDER_ID" >> ./vue-app/.env.production.local
          echo "VUE_APP_GOOGLE_CLIENT_ID=$VUE_APP_GOOGLE_CLIENT_ID" >> ./vue-app/.env.production.local
          echo "VUE_APP_SENTRY_URL=$VUE_APP_SENTRY_URL" >> ./vue-app/.env.production.local

    - run:
        name: Build JAR
        command: |
          cd ./backend-app/ && ./gradlew clean build vueProd bootJar

    - save_cache:
        paths:
        - ~/.gradle/wrapper
        key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

    - save_cache:
        paths:
        - ~/.gradle/caches
        key: v1-gradle-cache-{{ checksum "build.gradle" }}

    - store_artifacts:
        path: build/libs
workflows:
  version: 2
  workflow:
    jobs:
    - build
