version: 2
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    docker:
    - image: circleci/openjdk:8u212-stretch

    steps:
    - checkout

    - restore_cache:
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - restore_cache:
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

    - run:
        name: Fill .env.production.local
        command: |
          echo "VUE_APP_BACKEND_URL=$VUE_APP_BACKEND_URL" > ./vue-app/.env.production.local
          echo "VUE_APP_GOOGLE_CLIENT_ID=$VUE_APP_GOOGLE_CLIENT_ID" >> ./vue-app/.env.production.local
          echo "VUE_APP_SENTRY_URL=$VUE_APP_SENTRY_URL" >> ./vue-app/.env.production.local
          echo "VUE_APP_VAPID_PUBLIC_KEY=$VUE_APP_VAPID_PUBLIC_KEY" >> ./vue-app/.env.production.local

    - run:
        name: Dockerize backend app
        command: |
          cd ./backend-app
          ./gradlew --console=plain clean build jib -Djib.to.image=$DOCKER_REGISTRY_URL/konkit/altszama:$CIRCLE_BUILD_NUM -Djib.to.auth.username=$DOCKER_REGISTRY_USER -Djib.to.auth.password=$DOCKER_REGISTRY_PASS
          cd ../

    # - run: docker push konkit/altszama:$CIRCLE_BUILD_NUM
    - setup_remote_docker

    - run: echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY_URL --username $DOCKER_REGISTRY_USER --password-stdin

    - run:
        name: Dockerize frontend app
        command: |
          cd ./vue-app
          docker build . -t konkit/altszama-frontend
          cd ../

    - run: docker tag konkit/altszama-frontend $DOCKER_REGISTRY_URL/konkit/altszama-frontend:$CIRCLE_BUILD_NUM

    - run: docker push $DOCKER_REGISTRY_URL/konkit/altszama-frontend:$CIRCLE_BUILD_NUM

    - save_cache:
        paths:
        - ~/.gradle/wrapper
        key: v1-gradle-wrapper-{{ checksum "backend-app/gradle/wrapper/gradle-wrapper.properties" }}

    - save_cache:
        paths:
        - ~/.gradle/caches
        key: v1-gradle-cache-{{ checksum "backend-app/build.gradle" }}

  deploy:
    machine:
      enabled: true
    steps:
    - add_ssh_keys

    - run:
        name: known_hosts sadness
        command: ssh-keyscan -H $SITE_SSH_HOST >> ~/.ssh/known_hosts

    - run:
        name: Replace linked jar to run
        command: |
          ssh $SITE_SSH_USER@$SITE_SSH_HOST "cd /var/app/altszama && docker-compose down && docker-compose up -d"

    # - run:
    #     name: Restart app
    #     command: |
    #       ssh $SITE_SSH_USER@$SITE_SSH_HOST "$RESTART_APP_COMMAND"
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
